[build]
  publish = "packages/site/dist"
  functions = "packages/functions/dist"
  build = "yarn build"

[dev]
  command = "yarn start"
  port = 1234
  targetPort = 3000
  publish = "packages/site/dist"
  functions = "packages/functions/dist"
