[build]
  publish = "packages/site/dist"
  functions = "packages/functions/dist"
  build = "yarn build"

[dev]
  command = "yarn start"
  port = 1234
  targetPort = 3000
  publish = "packages/site/dist"
  functions = "packages/functions/dist"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat?authorization=:authorization'
  status = 200
  force = true
  query = { authorization = ":authorization" }

[[redirects]]
  from = '/*/main.js'
  to = '/main.js'
  status = 200
  force = true

[[redirects]]
  from = '/*'
  to = '/'
  status = 200
